### ISSUE TITLE
Add VSMSettings struct

### ISSUE THREAD

**Issue by ufechner7** [Albatross-Kite-Transport/VortexStepMethod.jl#84]
Settings should be separated from code. Settings should be stored in a yaml file.

Possible content

- number of panels
- cord
- span
- vector to the origin of the kite body frame
- air density
- mass
- inertia tensor

We could also not include mass and inertia if we say that this is outside of the scope of this package.

**Comment by 1-Bart-1** [comment]
The idea with moving things to a file being that you don't have to know Julia to use the package?

**Comment by ufechner7** [comment]
Well, all our simulation software should use yaml files (or other file times for time series data) as input. That is at least what we discussed in Delft. While in theory this means you do not need to know Julia to run a simulation, in practice you will not get very far without knowing Julia.

**Comment by ufechner7** [comment]
> Does this mean that you want to separate kite geometry to a csv file as well?

I don't think a csv file is a good file format for the kite geometry, but I did not have a look yet at what my colleagues did.

**Comment by ufechner7** [comment]
> But we should at least keep the option to use code for generating the kite geometry.

Well, what I am doing in KiteUtils is to read a yaml file into a struct. And the struct can be modified at runtime.

A struct is only needed if fast access to the data is needed, otherwise a dictionary (or dict of dicts for a nested structure) is easier.

**Comment by 1-Bart-1** [comment]
I prefer you implement the settings in the same style as KiteUtils in order to keep consistency.

**Comment by ufechner7** [comment]
Suggestion from Jelle:
````
wing_settings:
    n_panels: 40
    spanwise_panel_distribution = "uniform"
solver_settings:
    aerodynamic_model_type:
    max_iterations:
    ....
````
and a separate struct VSMGeometry.

**Comment by 1-Bart-1** [comment]
> wings:
>     - main_wing:
>         n_panels: 40
>         spanwise_panel_distribution = "uniform"
>     - tail:
>         n_panels: 20
> solver_settings:
>     aerodynamic_model_type:
>     max_iterations:
>     ....

So what you want is one yaml file with three segments:
```
- wings
- solver
- body_aero
```
What do you do if you want to have multiple different body_aeros? Then you need multiple different files?
It is ok for me that we use .yaml files as input, but not as the only way of constructing the Solver, BodyAerodynamics and Wing. I still want to be able to use kwargs, without a settings file.

**Comment by ufechner7** [comment]
> What do you do if you want to have multiple different body_aeros?
I do not see a use-case for that. We have one aerodynamic body which can be composed of one or more wings.

**Comment by ufechner7** [comment]
Current suggestion:
```yaml
Model:
    VSM: Vortex Step Method
    LLT: Lifting Line Theory
PanelDistribution:
    LINEAR:             Linear distribution
    COSINE:             Cosine distribution
    COSINE_VAN_GARREL:  van Garrel cosine distribution
    SPLIT_PROVIDED:     Split provided sections
    UNCHANGED:          Keep original sections
InitialGammaDistribution:
    ELLIPTIC:           Elliptic distribution
    ZEROS:              Constant distribution

wings:
    - name: main_wing
      n_panels: 40
      n_groups: 40
      spanwise_panel_distribution: LINEAR
      spanwise_direction: [0.0, 1.0, 0.0]
      remove_nan: true
    - name: tail
      n_panels: 20
      n_groups: 20
      spanwise_panel_distribution: COSINE
      spanwise_direction: [0.0, 1.1, 0.0]
      remove_nan: false
solver_settings:
    n_panels: 40
    n_groups: 40
    aerodynamic_model_type: VSM
    density: 1.225                   # air density  [kg/m³]
    max_iterations: 1500
    rtol: 1e-5                       # relative error   [-]
    tol_reference_error: 0.001
    relaxation_factor: 0.03          # relaxation factor for convergence
    artificial_damping: false        # whether to apply artificial damping
    k2: 0.1                          # artificial damping parameter
    k4: 0.0                          # artificial damping parameter
    type_initial_gamma_distribution: ELLIPTIC
    core_radius_fraction: 1e-20
    mu: 1.81e-5                      # dynamic viscosity [N·s/m²]
    calc_only_f_and_gamma: false     # whether to only output f and gamma
```
